Ajuste de conteúdo sobre perfis Nisia
mastertech/Nisia pull request #12
Opened 2020-01-08 21:31 UTC by Diandralas

Houve alteração de perfis de Nisia, foi excluído o perfil de entusiasta e adicionado dois novos perfis: Apoiadores e Facilitadores, e alterado a nomenclatura de Educadora para Educadores.
Devido esta mudança a sessão de 'ecossistema' tornou-se obsoleto e foi retirado na home.

2020-01-08 22:00 UTC, lcsmelo-0 requested changes

2020-01-08 22:00 UTC, lcsmelo-0 commented on nisia_cadastro/static/css/style.css
>          height: 100vh;
Vh não funciona em mobile
Tenta fazer `window.innerHeight` em CSS inline.

2020-01-08 22:00 UTC, lcsmelo-0 commented on nisia_cadastro/templates/index.html
> +                <img src="{% static 'img/facilitadores.png' %}" alt="">
Preencher `alt`

2020-01-08 22:00 UTC, lcsmelo-0 commented on nisia_cadastro/templates/index.html
> +                <img src="{% static 'img/apoiadores.png' %}" alt="">
Preencher `alt`

2020-01-08 22:00 UTC, lucasmelo18 commented on nisia_cadastro/templates/index.html
> +            <button id="mulheres__b__g" class="accordion" data-aos="fade-up" data-aos-duration="2000"> <img class="mulheres__a__svg" src="{% static 'img/symbols11.svg' %}"> OS APOIADORES</button>
Preencher `alt`

2020-01-08 22:40 UTC, Diandralas commented on nisia_cadastro/static/css/style.css
>          height: 100vh;
item retirado pois não está no html

2020-01-09 13:15 UTC, lcsmelo-0 submitted a review, later dismissed

2020-01-09 16:55 UTC, brunoapimentel approved these changes

2020-01-09 16:55 UTC, merged