Form submit
mastertech/Nisia pull request #4
Opened 2019-07-25 21:33 UTC by ericbgauch

- Utilizar form do Django e adaptar o existente no front
- Fazer validação dos campos
- Verificar se email ja esta cadastrado

Ps: minhas alterações no 'demob.js' foram das linhas 9 a 63

2019-07-25 22:50 UTC, fmoraes-dev requested changes

2019-07-25 22:50 UTC, felipetm6 commented on nisia_cadastro/static/js/demob.js
> +    if (document.cookie && document.cookie !== '') {
A expressão `document.cookie` já valida se ele é `undefined`, `null` ou uma String vazia, então o `document.cookie !== ''` é desnecessário.

2019-07-25 22:50 UTC, felipetm6 commented on nisia_cadastro/views.py
> +        msg = {"status": 500, "result": "invalid method"}
Se é um erro de método não era melhor passar o código `405`?

2019-07-26 13:55 UTC, ericbgauch commented on nisia_cadastro/views.py
> +        msg = {"status": 500, "result": "invalid method"}
POURRA tava testando uma outra bagaça e esqueci de mudar

2019-07-26 13:55 UTC, ericbgauch commented on nisia_cadastro/static/js/demob.js
> +    if (document.cookie && document.cookie !== '') {
justo

2019-07-26 13:58 UTC, merged